import { PlayerClassConfig, PlayerClassId } from '../types';

export const PLAYER_CLASSES: Record<PlayerClassId, PlayerClassConfig> = {
  warrior: {
    id: 'warrior',
    name: 'Guerrero',
    title: 'Defensor de Hierro',
    description: 'Robusto y letal cuerpo a cuerpo. Gran cantidad de vida y armadura pesada.',
    icon: '🛡️',
    baseHp: 100,
    baseMp: 20,
    baseAtk: 14,
    baseDef: 6,
    baseCrit: 8,
    visionRadius: 6,
    skillName: 'Golpe Sísmico',
    skillDescription: 'Golpea el suelo infligiendo 220% de daño a todos los enemigos adyacentes y los aturde.',
    skillCooldown: 5,
    skillCostMp: 8,
  },
  mage: {
    id: 'mage',
    name: 'Mago',
    title: 'Invocador de las Sombras',
    description: 'Maestro de lo arcano. Fragil en combate físico pero con inmenso poder destructivo a distancia.',
    icon: '🔮',
    baseHp: 65,
    baseMp: 60,
    baseAtk: 10,
    baseDef: 2,
    baseCrit: 12,
    visionRadius: 7,
    skillName: 'Ráfaga Arcana',
    skillDescription: 'Lanza un proyectil místico a hasta 5 casillas que impacta causando daño mágico devastador.',
    skillCooldown: 4,
    skillCostMp: 12,
  },
  rogue: {
    id: 'rogue',
    name: 'Pícaro',
    title: 'Cazador de Sombras',
    description: 'Sigiloso y veloz. Excelente visión en la oscuridad y letales golpes críticos.',
    icon: '🗡️',
    baseHp: 75,
    baseMp: 35,
    baseAtk: 12,
    baseDef: 3,
    baseCrit: 24,
    visionRadius: 8,
    skillName: 'Paso Sombrío',
    skillDescription: 'Se desvanece en las sombras, salta 3 casillas e incrementa el crítico a 100% por 1 turno.',
    skillCooldown: 4,
    skillCostMp: 10,
  },
};
